name: reviewdog
on: [pull_request]
jobs:
  stylelint:
    name: runner / stylelint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run stylelint with reviewdog
        uses: reviewdog/action-stylelint@v1.11.0
        with:
          github_token: ${{ secrets.TOKEN }}
          packages: 'stylelint-config-standard-scss'
          reporter: github-pr-review
          stylelint_input: src/**/*.{scss,css,sass}
          stylelint_config: configs/.stylelintrc.json
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - name: Run eslint with reviewdog
      - uses: actions/checkout@v2
      - uses: reviewdog/action-eslint@v1.14.0
        with:
          github_token: ${{ secrets.TOKEN }}
          reporter: github-pr-review
